//! What `--version` prints: the app, then what it is built on.

// LIBRARIES: the Rust crates and frontend libraries in the build, generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/libraries.rs"));

/// The app version, then the WebView2 runtime (`None` if it can't be found)
/// and the libraries, one per line.
pub fn text(webview: Option<&str>) -> String {
    let rows: Vec<(&str, &str)> = std::iter::once(("WebView2", webview.unwrap_or("not found"))).chain(LIBRARIES.iter().copied()).collect();
    let width = rows.iter().map(|(name, _)| name.len()).max().unwrap_or(0);
    let mut text = format!("Simple Reader {}", env!("CARGO_PKG_VERSION"));
    for (name, version) in rows {
        text += &format!("\n  {name:<width$}  {version}");
    }
    text
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The (name, version) columns of each line after the first.
    fn rows(text: &str) -> Vec<(String, String)> {
        let row = |line: &str| {
            let (name, version) = line.trim_start().split_once(char::is_whitespace).unwrap();
            (name.to_string(), version.trim_start().to_string())
        };
        text.lines().skip(1).map(row).collect()
    }

    #[test]
    fn lists_the_app_runtime_and_libraries() {
        let text = text(Some("140.0.1"));
        assert_eq!(text.lines().next().unwrap(), format!("Simple Reader {}", env!("CARGO_PKG_VERSION")));
        let expected: Vec<(String, String)> = [("WebView2", "140.0.1")]
            .iter()
            .chain(LIBRARIES)
            .map(|(name, version)| (name.to_string(), version.to_string()))
            .collect();
        assert_eq!(rows(&text), expected);
        for name in ["tauri", "foliate-js", "mermaid"] {
            assert!(LIBRARIES.iter().any(|(n, v)| *n == name && !v.is_empty()), "{name} missing");
        }
    }

    #[test]
    fn says_when_webview2_is_missing() {
        assert_eq!(rows(&text(None))[0], ("WebView2".to_string(), "not found".to_string()));
    }
}
