//! What `--version` prints: the app, then what it is built on.

// LIBRARIES: the bundled frontend libraries, generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/libraries.rs"));

/// The app version, then Tauri, the WebView2 runtime (`None` if it can't be
/// found) and the bundled libraries, one per line.
pub fn text(webview: Option<String>) -> String {
    let mut rows = vec![
        ("Tauri", tauri::VERSION.to_string()),
        ("WebView2", webview.unwrap_or_else(|| "not found".into())),
    ];
    rows.extend(
        LIBRARIES
            .iter()
            .map(|&(name, version)| (name, version.to_string())),
    );
    let width = rows.iter().map(|(name, _)| name.len()).max().unwrap_or(0);
    let mut text = format!("Simple Reader {}", env!("CARGO_PKG_VERSION"));
    for (name, version) in rows {
        text += &format!("\n  {name:<width$}  {version}");
    }
    text
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lists_the_app_runtime_and_libraries() {
        let text = text(Some("140.0.1".into()));
        let lines: Vec<&str> = text.lines().collect();
        assert_eq!(
            lines[0],
            format!("Simple Reader {}", env!("CARGO_PKG_VERSION"))
        );
        assert!(lines.contains(&"  WebView2      140.0.1"));
        for name in ["Tauri", "foliate-js", "marked", "mermaid", "highlight.js"] {
            assert!(
                lines.iter().any(|line| line.trim_start().starts_with(name)),
                "{name} missing:\n{text}"
            );
        }
        assert!(LIBRARIES.iter().all(|(_, version)| !version.is_empty()));
    }

    #[test]
    fn says_when_webview2_is_missing() {
        assert!(text(None).contains("WebView2      not found"));
    }
}
